[notebook]
dir = "~/Notes"

[note]
language = "en"
filename = "{{format-date now 'timestamp'}}-{{slug title}}"
extension = "md"

[group.daily]
paths = ["daily/**"]
[group.daily.note]
filename = "{{format-date now}}"
template = "daily.md"

[group.tickets]
paths = ["tickets/**"]
[group.tickets.note]
filename = "{{title}}"
template = "ticket.md"
